# Generated by Django 2.1.dev20180407004606 on 2018-07-11 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('jira_key', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('host', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('pre_calculated_attendance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventAudienceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STA', 'Academic Support Staff'), ('FAC', 'Faculty'), ('GRA', 'Graduate Students')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DIA', 'Dialogue'), ('WKS', 'Workshop'), ('MUP', 'Meetup'), ('SYM', 'Symposium'), ('COL', 'Colloquium'), ('MET', 'Meeting'), ('FME', 'Faculty Meeting'), ('WEB', 'Webinar')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=25)),
                ('last_name', models.CharField(blank=True, max_length=25)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('add_to_mailing_list', models.BooleanField(null=True)),
                ('rfid', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('join_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('STA', 'Staff'), ('FAC', 'Faculty'), ('INS', 'Instructor'), ('STU', 'Student'), ('GST', 'Guest'), ('CNS', 'Consultant')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('short_name', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.NullBooleanField(default=True)),
                ('list_priority', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.Event')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.Person')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reception.Service')),
            ],
            options={
                'verbose_name': 'Sign-in',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='affiliation_type',
            field=models.ManyToManyField(to='reception.PersonType'),
        ),
        migrations.AddField(
            model_name='event',
            name='audience_type',
            field=models.ManyToManyField(to='reception.EventAudienceType'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ManyToManyField(to='reception.EventType'),
        ),
    ]
