# Generated by Django 2.1.dev20180407004606 on 2018-07-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audience_type',
            field=models.ManyToManyField(blank=True, to='reception.EventAudienceType'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ManyToManyField(blank=True, to='reception.EventType'),
        ),
        migrations.AlterField(
            model_name='person',
            name='add_to_mailing_list',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes'), ('A', 'Added')], default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
