# Generated by Django 2.1.dev20180407004606 on 2018-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_auto_20180711_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='add_to_mailing_list',
            field=models.CharField(blank=True, choices=[('N', 'No'), ('Y', 'Yes'), ('A', 'Added')], max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='affiliation_type',
            field=models.ManyToManyField(blank=True, to='reception.PersonType'),
        ),
    ]
