# Generated by Django 2.1.dev20180407004606 on 2018-07-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_auto_20180711_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='rfid',
            field=models.CharField(blank=True, default='', max_length=12),
            preserve_default=False,
        ),
    ]
