# Generated by Django 2.1.dev20180407004606 on 2018-07-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_auto_20180716_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
