# Generated by Django 2.1.dev20180407004606 on 2018-07-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_auto_20180723_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pre_calculated_attendance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
